### ISSUE TITLE
Peek definition doesn't go to proper place

### ISSUE THREAD

**Issue by johnnywz00** [toerob/vscode-tads3tools#17]
When I command-click on a method name, the peek definition will usually take me to some other object in my game that also overrides that method. 

It would be great if the editor could determine the most recent place in that particular object's inheritance tree where the method was defined. 

For instance: 

class A: Thing
     getDropDestination(obj,path) {  //code that's different from Thing// }
;
obj1: A
    anotherMethod {  code;
              code;
              return getDropDestination(var, var); }              // <--if I click on this symbol, peek definition might take me to obj2.
                                                                                        // Should take me to class A's definition
;
//another source file
obj2: Thing
    getDropDestination(obj,path) { //code that's different from Thing and Class A }

**Comment by toerob** [comment]
I agree! This definitely should be fixed! 

While on this topic I have a related one:  I trying to decide how to treat modified objects. As it is now, you get a peek of all modifications, instead of just going to the most recent one. I could fix it so you'd go to the most recent one and peeking on that one the next in the chain,  but it's not obvious to me what the best user experience is here and I right now I think I prefer seeing all modifications at once. 

Do you perhaps have any input on this as well?

**Comment by johnnywz00** [comment]
I guess I'm not sure without trying both ways. I think that as long as everything shown is part of the clicked object's direct ancestry, it should be good. It's when "cousin" or "sibling" overrides get shown that make it confusing...
