### ISSUE TITLE
Parsing fails: no files to parse

### ISSUE THREAD

**Issue by JostSchenck** [toerob/vscode-tads3tools#3]
**Describe the bug**
When opening a project, parsing fails with the message "Parsing all files via makefile Makefile.t3m failed: No files to parse. Aborting operation". This happens with existing projects that can run on TADS 3 workbench, but also with a fresh project generated with vscode-tads3tools.

**To Reproduce**
1. Start VS Code
2. Open project folder

**Expected behavior**
Parsing should work, symbols should appear etc.

**Screenshots**
Not applicable

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version VS Code 1.59.1
 - vscode-tads3tools Released on
22.8.2021, 20:11:36
Last updated
27.8.2021, 20:02:36

**Additional context**
I corrected all paths in the settings to their windows counterparts, but the problem persists.

**Comment by toerob** [comment]
Hi! Thanks for the bug report!

I created a game with the tads3 workbench and then opened the same folder in vscode-tads3tools. Game was parsed and the outliner showed the result. So I need some additional info. 

Could you please check the logs from the language server by opening up View/Output and select “Tads3 Language Server” in the selector.

I’m suspecting an issue with folder privileges and/or file path, so at least it would be useful to know the path of the project? Have you tried creating a project in your user folder or anywhere else?

Otherwise it can be good to know that if the game can’t compile the first time around the parsing wont proceed either (but you should in that case see some diagnostics telling you why) So please verify you can also build the project.

**Comment by toerob** [comment]
One additional thought. Did you really use the “open folder” functionality or instead opened a single file within the folder?

**Comment by JostSchenck** [comment]
Thank you for the prompt response! Here are the logs from the language
server. Only thing I noticed somehow is the line where it prints "adv3Lite"
while I use "adv3" (I'm new to TADS, so I don't know much about
the difference).
If that helps, I've uploaded the zipped project (it's not large) to
https://drive.google.com/file/d/1ow6r71yCW-kAEX2FyIG0tNUfVYh9X6qo/view?usp=sharing

Thanks a lot
Jost

[Info  - 07:57:58] Trying to locate a default makefile
[Info  - 07:57:58] Found a makefile:
d:\Benutzerverzeichnisse\jost\Dokumente\TADS\HagdornMystery\HagdornMystery.t3m
[Info  - 07:57:58] Setting up t3 image monitor
[Info  - 07:57:58] Diagnosing
[Info  - 07:57:58] Diagnosing went by with no errors
[Info  - 07:57:58] Preprocess and parse all documents
Done analyzing makefile
adv3Lite
Ensuring "c:\Users\Windows\AppData\Roaming\Code\User\globalStorage\toerob.vscode-tads3tools"
exists
Ensuring "c:\Users\Windows\AppData\Roaming\Code\User\globalStorage\toerob.vscode-tads3tools\.cache\adv3"
exists
0 number of preprocessed lines mapped in 0 ms
Counting row lines done in 0 ms
Postprocessing row lines done in 0 ms
No files to parse. Aborting operation
[Info  - 07:58:04] Last chosen editor changed to:
file:///d%3A/Benutzerverzeichnisse/jost/Dokumente/TADS/HagdornMystery/HagdornMystery.t
[Info  - 07:58:12] Last chosen editor changed to: output:tasks
[Info  - 07:58:16] Last chosen editor changed to:
file:///d%3A/Benutzerverzeichnisse/jost/Dokumente/TADS/HagdornMystery/HagdornMystery.t
[Info  - 07:58:20] Last chosen editor changed to:
output:extension-output-toerob.vscode-tads3tools-%231


Am Fr., 3. Sept. 2021 um 07:36 Uhr schrieb Tomas Öberg <
***@***.***>:

**Comment by JostSchenck** [comment]
Yes, I used "open folder"

Am Fr., 3. Sept. 2021 um 08:01 Uhr schrieb Tomas Öberg <
***@***.***>:

**Comment by toerob** [comment]
I see, that explains it. My algorithm for deciding which type of project it seems to need some tweaking. Many thanks for the files. I’ll take a look during weekend and fix it.

**Comment by JostSchenck** [comment]
Great, thanks a lot!

Tomas Öberg ***@***.***> schrieb am Fr., 3. Sept. 2021, 09:45:

**Comment by toerob** [comment]
I did a few different changes. (All related to the differencies between windows vs unix/linux file path conventions.) Your project parses fine now on my machine, if it still doesn't on your machine, try to **clear the cache** first (via the command to do so) and then either restart vscode or run the command to **set the makefile** (if there's only one you won't get to choose). That should trigger a reparse of all library files. (Might take a minute or so.)  

I'll keep testing around for more bugs until I do a proper release this weekend (I have a few other things that I might possibly want to include as well until then).  _But_ if you like you can try and see if this (preview) vsix-package works better until then. If you do that, remember to uninstall the first extension first before installing this. And please let me know if it either works better or worse.

https://drive.google.com/file/d/1KINbK3jVx5f9SRjMXrHX_BPMUg4fW62s/view?usp=sharing

(https://code.visualstudio.com/docs/editor/extension-marketplace#_install-from-a-vsix)

**Comment by JostSchenck** [comment]
Thanks! I tried and it doesn't work yet, unfortunately. Same error message,
here's the logs, it now correctly recognizes the library:
[Info  - 18:42:59] Trying to locate a default makefile
[Info  - 18:42:59] Found a makefile:
d:\Benutzerverzeichnisse\jost\Dokumente\TADS\HagdornMystery\HagdornMystery.t3m
[Info  - 18:42:59] Setting up t3 image monitor
[Info  - 18:42:59] Diagnosing
[Info  - 18:42:59] Diagnosing went by with no errors
[Info  - 18:42:59] Preprocess and parse all documents
Done analyzing makefile
Project using standard adv3 library
Ensuring "c:\Users\Windows\AppData\Roaming\Code\User\globalStorage\toerob.vscode-tads3tools"
exists
Ensuring "c:\Users\Windows\AppData\Roaming\Code\User\globalStorage\toerob.vscode-tads3tools\.cache\adv3"
exists
0 number of preprocessed lines mapped in 0 ms
Counting row lines done in 0 ms
Postprocessing row lines done in 0 ms
No files to parse. Aborting operation

Am Fr., 3. Sept. 2021 um 22:27 Uhr schrieb Tomas Öberg <
***@***.***>:

**Comment by JostSchenck** [comment]
I should have added: I did clear the cache and tried both setting makefile
as well as restarting VS Code.

Am Sa., 4. Sept. 2021 um 18:44 Uhr schrieb Jost Schenck <
***@***.***>:

**Comment by toerob** [comment]
That’s unfortunate. I should mention I had to change the files linked earlier since there was a few exits that weren’t defined and caused compilation to fail. “Hallway” for instance. But maybe this wasnt a complete set of files, just a portion of the game? 
other than that I wonder if you have set up global environment variables so the std libraries can be found, e.g

%TADS_HOME% - your tads3 folder
%TADS_HOME%\bin
%TADS_HOME%\include

I’m not entirely sure right now (and not at the computer), but I believe tads3 workbench have settings for this and doesn’t  depend on those global environment variables, but the vscode extension either needs that to be setup to get relative directories like adv3/adv3 to work, or use the -FI and/or -FL flag to setup the include/library folders with absolute paths. Hope that help. I’ll investigate further.

**Comment by toerob** [comment]
The easiest to check this is just to enter the game folder and run “t3make -f HagdornMystery.t3m” on the command line. If it can compile there the extension should work too.

**Comment by JostSchenck** [comment]
I very much appreciate your help, thank you! Maybe I found something.

First of all: I had sent all existing files -- I had just started this and
TADS would just give a warning but still compile, so I didn't think about
that. I now set the environment variables (before I had configured absolute
paths in the extension settings and thought that was enough) and restarted
vs code, “t3make -f HagdornMystery.t3m” does compile correctly. The error
persists with the same output.

However, after looking over the extension source code (the amateur way, I'm
not experienced in vs code extension and not even in
javascript/typescript), I turned on the "Parse only the workspace files"
setting to get the following debugging output:
Only parses files with base directory:
\Benutzerverzeichnisse\jost\Dokumente\TADS\HagdornMystery\hagdornmystery.t3m
On windows, however, this should begin with a drive letter, so in this case
it should read *D:*\Benutzerverzeichnisse\jost\Dokumente\TADS\HagdornMystery\hagdornmystery.t3m

I'm pretty much sure this is the problem.

Am Sa., 4. Sept. 2021 um 20:50 Uhr schrieb Tomas Öberg <
***@***.***>:

**Comment by toerob** [comment]
And I appreciate your help! This is really valuable feedback and exactly what I need to make the extension better. I had similar issues before when trying to adapt the extension for windows, the way file paths got rendered vs on linux/mac. I had mistakingly used URI.parse instead of URI.file here, same as then. I just don't get why it works here for me. I even put the project on an exactly similar path on my d: drive, and still it parsed through. But never mind that. I compiled another VSIX if you like to try. This one sets the base-directory correctly. 

https://drive.google.com/file/d/1oW6AbnqYq_velKZNOt1eFj3pRMhPbu1b/view?usp=sharing

**Comment by JostSchenck** [comment]
Getting closer, but still doesn't find anything...
[Info  - 00:02:13] Trying to locate a default makefile
[Info  - 00:02:13] Found a makefile:
d:\Benutzerverzeichnisse\jost\Dokumente\TADS\HagdornMystery\hagdornmystery.t3m
[Info  - 00:02:13] Setting up t3 image monitor
[Info  - 00:02:13] Diagnosing
[Info  - 00:02:13] Diagnosing went by with no errors
[Info  - 00:02:13] Preprocess and parse all documents
Done analyzing makefile
Project using standard adv3 library
Ensuring "c:\Users\Windows\AppData\Roaming\Code\User\globalStorage\toerob.vscode-tads3tools"
exists
Ensuring "c:\Users\Windows\AppData\Roaming\Code\User\globalStorage\toerob.vscode-tads3tools\.cache\adv3"
exists
0 number of preprocessed lines mapped in 0 ms
Counting row lines done in 0 ms
Postprocessing row lines done in 0 ms
Settin up base directory for project:
d:\Benutzerverzeichnisse\jost\Dokumente\TADS\HagdornMystery
Only parses files with base directory:
d:\Benutzerverzeichnisse\jost\Dokumente\TADS\HagdornMystery
****
****

No files to parse. Aborting operation

Am Sa., 4. Sept. 2021 um 23:59 Uhr schrieb Tomas Öberg <
***@***.***>:

**Comment by JostSchenck** [comment]
I compiled the current github version to experiment a little bit and it
seems not just about the base directory, but the preprocessedFilesCacheMap
isn't populated with any paths in the first place.
I've never developed a VS Code extension and I have no idea how to properly
debug these to understand what happens :)
The jest tests at least all pass here.

Am So., 5. Sept. 2021 um 00:04 Uhr schrieb Jost Schenck <
***@***.***>:

**Comment by toerob** [comment]
Seems to be failing with the preprocessing,

I'm wondering what happens if you run the command:

```t3make -P -q -f "d:\Benutzerverzeichnisse\jost\Dokumente\TADS\HagdornMystery\HagdornMystery.t3m"```

in a command line terminal (for instance in vscode) exactly as it is written? 

If it works you should see a seemingly endless stream of preprocessed text running by (that you can abort with ctrl-c)

If it fails with some error message it might be that t3make cannot be reached globally, in that case either add a global enviroment path for your install directory of tads3,  e.g: "C:\Program Files\TADS3" or change the setting tads3.compiler.path in the extension settings in vscode to the absolute path, e.g: "C:\Program Files\TADS3\t3make.exe"

**Comment by JostSchenck** [comment]
I did this and it looks fine to me, just endless preprocessor output.

Am So., 5. Sept. 2021 um 00:43 Uhr schrieb Tomas Öberg <
***@***.***>:

**Comment by toerob** [comment]
Hm, I'll continue tomorrow. Would be interesting to see if you can fetch a few "#line <filepath>" from that output, I wonder if it somehow can't parse that line how the path might in that case look different on your system. Some debugging around on line 55, 56 might reveal what goes wrong.

**Comment by JostSchenck** [comment]
Here's the output:
https://drive.google.com/file/d/1OWPPojdkgGLAHLpRrV7qS4HF9o9u0K-u/view?usp=sharing
Seeing some '\n' I wondered whether this might be some unix vs windows line
feed problem, but a result.split(/\r?\n/)  instead of /\n/ didn't help.

Am So., 5. Sept. 2021 um 00:50 Uhr schrieb Jost Schenck <
***@***.***>:

**Comment by JostSchenck** [comment]
I'm embarrassed. I obviously didn't know that in VS code settings a path
should be enclosed in quotes, when there are spaces in there (which there
always are in windows "Program (x86)" directory). Adding quotes there let
the rest pass.
Symbol outline doesn't show up after parsing, but that'll be another
problem. I am sorry to have wasted so much of your time ...

Am So., 5. Sept. 2021 um 00:58 Uhr schrieb Tomas Öberg <
***@***.***>:

**Comment by toerob** [comment]
Which path. “t3make”? No problems at all, we have found several bugs thanks to this conversation! And the extension should adapt to its users, not the other way around. I’m thinking it might be good to add a few control checks here and there to validate paths and that t3make can be found etc...

**Comment by toerob** [comment]
I’m going to change this row:

const commandLine = `${t3makeCompilerPath} -P -q -f "${chosenMakefilePath}"`;

To:

const commandLine = `”${t3makeCompilerPath}” -P -q -f "${chosenMakefilePath}"`;

Users shouldn’t need to bother with broken paths :)

**Comment by JostSchenck** [comment]
Perfect. Thanks a lot for offering such a tool for free and being that
engaged with it :)

Am So., 5. Sept. 2021 um 07:50 Uhr schrieb Tomas Öberg <
***@***.***>:

**Comment by toerob** [comment]
You are welcome! What can I say :) I truly care for tads3 and I wish to lower the treshold for newcomers, in order for them to see how great the system is. I think it truly deserves that! 

No progress with the outliner though? I like suggest a clear cache and restart if you haven't already tried that.

**Comment by JostSchenck** [comment]
Interestingly, the visual editor worked for a while (and looked cool!), but
now only finds the starting room anymore; when trying to parse again, I get
the message that it cannot reparse now, since a full project parsing is
already in progress Try again later.

[Info  - 11:48:43] Refresh map view
[Info  - 11:48:43] Updating webview with new symbols
Found symbol: hallway
[Info  - 11:48:50] Diagnosing
[Info  - 11:48:50] Diagnosing went by with no errors
[Info  - 11:48:50] Skipping parsing since long processing is in action
Found symbol: hagdornMuhrenkamp
[Info  - 11:49:14] Diagnosing
[Info  - 11:49:14] Diagnosing went by with no errors
[Info  - 11:49:14] Skipping parsing since long processing is in action
[Error - 11:49:19] Cannot connect rooms: frontOfHouse with undefined
via west/east
Found symbol: hagdornAdolfstrasse
[Info  - 11:49:35] Diagnosing
[Info  - 11:49:35] Diagnosing went by with no errors
[Info  - 11:49:35] Skipping parsing since long processing is in action
[Error - 11:49:39] Cannot connect rooms: frontOfHouse with undefined
via east/west
[Info  - 11:49:48] Last chosen editor changed to:
file:///d%3A/Benutzerverzeichnisse/jost/Dokumente/TADS/HagdornMystery/HagdornMystery.t
[Info  - 11:49:56] Refresh map view
[Info  - 11:49:56] Updating webview with new symbols
[Info  - 11:49:56] Updating webview with new symbols
[Info  - 11:49:57] Updating webview with new symbols
[Info  - 11:49:58] Updating webview with new symbols
[Info  - 11:49:58] Updating webview with new symbols
[Info  - 11:50:09] Last chosen editor changed to:
output:extension-output-toerob.vscode-tads3tools-%231
[Info  - 11:51:27] Last chosen editor changed to:
file:///d%3A/Benutzerverzeichnisse/jost/Dokumente/TADS/HagdornMystery/HagdornMystery.t
[Info  - 11:51:35] Diagnosing
[Info  - 11:52:39] Last chosen editor changed to:
output:extension-output-toerob.vscode-tads3tools-%231


Am So., 5. Sept. 2021 um 11:41 Uhr schrieb Jost Schenck <
***@***.***>:

**Comment by toerob** [comment]
Alright .I had to change the following exits in the code you sent to make it compile, since the source code was missing hallway, kitchen, backhouseKitchen and passage.  (Not sure if I'm sitting on stale data though.)

```
passageway: Room
    //west = hallway
;

courtyard: OutdoorRoom
    //north = kitchen
    //south = backhouseKitchen
    //southeast = passage
;
```
But if those are missing I think you should see diagnostics about that in View/Problems

**Comment by JostSchenck** [comment]
Yes, I also fixed this, when the parser complained. But the symbols still
aren't visi le

Tomas Öberg ***@***.***> schrieb am So., 5. Sept. 2021, 13:10:

**Comment by toerob** [comment]
If the longprocessing is still active and not letting you reparse on save it can either be the cause of two cases:

* The longprocessing is not yet done (but then you should see the progress at the bottom of the window)

* Some error case that I didn't cover for has happened that leaves the longprocessing flag not to be reset as it should. (If the connection between the client/server happens for instance)

In the latter case, be on the lookout for any error dialogs or messages prior to getting the long processing errors. (Suggestion would be to restart the editor if that happens and try parsing it again)

I have a lot of changes done in the branch "next", if you run the extension in debug mode be sure to use that branch.  Otherwise this is the compiled version (same link as before): https://drive.google.com/file/d/1oW6AbnqYq_velKZNOt1eFj3pRMhPbu1b/view?usp=sharing

I hope for progress. Otherwise I suggest we arrange a short meeting later today and try to sort it out with a screenshare if you like to do that. I believe that might be most efficient.

**Comment by JostSchenck** [comment]
There's no progress shown and there are no errors -- in fact I see endless
"Adding <symbol> for <file>" lines in the language server output.
I switched to current next branch, cleared cache and all that, map works
again now. I notice that added connection sometimes get misplaced in code,
but it shows up.
The outline structure still doesn't show up.
If arranging a meeting is okay with you, I'd be happy about this. My 12
year old daughter is getting excited about TADS, too, and we have high
hopes for a modern IDE :)
I'm pretty much free all day today.

Am So., 5. Sept. 2021 um 13:41 Uhr schrieb Tomas Öberg <
***@***.***>:

**Comment by toerob** [comment]
Sounds good, my email is: tomaserikoberg@gmail.com

**Comment by JostSchenck** [comment]
I did clear the cache and restart several times. The outline only shows the
message "Loading document symbols for 'hagdornmystery.t'".

Am So., 5. Sept. 2021 um 09:25 Uhr schrieb Tomas Öberg <
***@***.***>:

**Comment by toerob** [comment]
Yes. I forgot one Map, the preprocessedCacheMap needs be case insensititive too
